### ISSUE TITLE
metabolomics integration

### ISSUE THREAD

**Issue by cvitlanko** [EPFL-LCSB/pytfa#11]
Hi,

do you plan to implement the integration of metabolomics (absolute metabolite concentrations) for dG calculation?

**Comment by psalvy** [comment]
Hi Svetlana,
I am not sure what you mean by your question. Concentrations (in log form) are part of the TFA formulation as variables. That means that if you know that your concentration of ATP is, for example, between 5e-3 and 3e-2, you can write (assuming correct ids, variable names etc):

```python
from math import log
mymodel.log_concentrations.atp_c.variable.lb = log(5e-3)
mymodel.log_concentrations.atp_c.variable.ub = log(3e-2)
```

This will constrain the dG according to your concentration measurements for cytosolic ATP.
As a reminder, the dG (not the dGo) takes activity (here, concentrations) into account for its calculation. You can find a more detailed explanation in those papers:
* Henry, Christopher S., Linda J. Broadbelt, and Vassily Hatzimanikatis. "Thermodynamics-based metabolic flux analysis." Biophysical journal 92.5 (2007): 1792-1805.
* Soh, Keng Cher, Ljubisa Miskovic, and Vassily Hatzimanikatis. "From network models to network responses: integration of thermodynamic and kinetic properties of yeast genome-scale metabolic networks." FEMS yeast research 12.2 (2012): 129-143.

**Comment by cvitlanko** [comment]
Hi, this is exactly what I mean, thanks.
Correct way would be to run like that, without `s` in the end. Just for the record if someone will be looking for this function.
`from math import log
mymodel.log_concentration.atp_c.variable.lb = log(5e-3)
mymodel.log_concentration.atp_c.variable.ub = log(3e-2)`

**Comment by psalvy** [comment]
Oh yes, my bad. Thank you for your question, I will add this to the documentation :)
Cheers,
Pierre
