### ISSUE TITLE
tutorial_basics lots of warnings when mytfa.prepare() 

### ISSUE THREAD

**Issue by Dahlai** [EPFL-LCSB/pytfa#39]
Dear pytfa team,
I'd like to try pytfa for some analysis.

I started by working through the tutorial_basics.py. When running the script, it throws a lot of 'Warning : NULL/U' and 'Warning : Null/L' messages at me during the mytfa.prepare() step.

Can you explain the meaning of these warnings, is it expected behavior?

Thanks a lot.

Cheers,
Michael

**Comment by psalvy** [comment]
Ciao Michael,
Thank you for reaching out to us ! And sorry for the late reply. Yes, these warnings actually come from Cobra while reading non-canonical chemical formulas, some of them have "FULL" in them. F is interpreted as Fluorine, but the U and L raise warnings. 
Hope it helps ! And feel free to ask more questions :)
Cheers,
Pierre

**Comment by Dahlai** [comment]
Thank you, Pierre, for the answer!
