### ISSUE TITLE
Get new delta G values after adding metabolomics data

### ISSUE THREAD

**Issue by sulheim** [EPFL-LCSB/pytfa#43]
How can I get the effective delta G of each reaction after the log concentration of all metabolites have been included?

**Comment by realLCSB** [comment]
Good day Sulheim,

You can access the Gibbs free energy of each reaction through the following commands:

```python
solution = model.optimize()
solution.raw.loc[model.delta_g.get_by_id(my_reaction_name).name]
# -- OR, after the model has been optimized and no changes have been made to it --
model.delta_g.get_by_id(my_reaction_name).primal
```

Note that the may `model.delta_g` works is the same as `model.reactions`. So if you're interested in PGI for instance, you can type `model.delta_g.PGI`.

Finally, I would like to stress that the Gibbs free energy value you will get is only one solution, you should perform a variability analysis (with your physiology constrained) to have an idea of the feasible range for the value.

Hope it helps,
Cheers,
Pierre
