### ISSUE TITLE
Use displacement or not?

### ISSUE THREAD

**Issue by sulheim** [EPFL-LCSB/pytfa#44]
Hi!

In the basic tutorial the ThermoModel is converted without thermodynamic displacement, while you use _add_displacement = True_ in some of the other tutorials and in the scripts creating the figures. Could you please explain the recommended use and how this affects the TFA / Flux variability calculations?

**Comment by psalvy** [comment]
Hello Sulheim!

Thanks for using our software! 
The ```add_displacement``` option simply adds a variable equal to DeltaG/RT, which represents the displacement from the thermodynamic equilibrium of a reaction. You can see it happening in details [here in the code](https://github.com/EPFL-LCSB/pytfa/blob/master/pytfa/thermo/tmodel.py#L534). Also, if you are unsure what displacement from equilibrium means, you can check it out [here](https://en.wikipedia.org/wiki/Chemical_equilibrium).
So, unless you displacement is close to the bigM values used in pyTFA, adding these as a constraint will not change anything to your model (might take a little while longer to solve, but that is all).

Hope that helps!

Cheers,
Pierre
